src/AppBundle/Entity/Journal.php
<?php

/*
 * Copyright (C) 2015-2016 Michael Joyce <ubermichael@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace AppBundle\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Journal.
 *
 * Any OJS journal may make deposits to the PLN.
 *
 * @ORM\Table(name="journal")
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity(repositoryClass="JournalRepository")
 */
class Journal
{
    /**
     * List of states where a deposit has been sent to LOCKSSOMatic.
     *
     * This should be a constant array, but those aren't supported in PHP 5.4.
     *
     * @var array
     */
    public static $SENTSTATES = array(
            'deposited',
            'complete',
            'status-error',
        );

    /**
     * The URL suffix for the ping gateway, appened to the Journal's URL for the
     * ping.
     *
     * @todo remove this, and use the gateway url reported in deposits
     */
    const GATEWAY_URL_SUFFIX = '/gateway/plugin/PLNGatewayPlugin';

    /**
     * Database ID.
     *
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * Journal UUID, as generated by the PLN plugin.
     *
     * @var string
     * @ORM\Column(type="string", length=36, nullable=false)
     */
    private $uuid;

    /**
     * When the journal last contacted the staging server.
     *
     * @var string
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $contacted;

    /**
     * OJS version powering the journal.
     *
     * @var string
     * @ORM\Column(type="string", nullable=true, length=12)
     */
    private $ojsVersion;

    /**
     * When the journal manager was notified.
     *
     * @var string
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $notified;

    /**
     * The title of the journal.
     *
     * @var string
     * @ORM\Column(type="string", nullable=false)
     */
    private $title;

    /**
     * Journal's ISSN.
     *
     * @var string
     * @ORM\Column(type="string", length=9, nullable=false)
     */
    private $issn;

    /**
     * The journal's URL.
     *
     * @var string
     *
     * @Assert\Url
     * @ORM\Column(type="string", nullable=false)
     */
    private $url;

    /**
     * The status of the journal's health. One of new, healthy, unhealthy,
     * triggered, or abandoned.
     *
     * @var string
     * @ORM\Column(type="string", nullable=false)
     */
    private $status = 'healthy';

    /**
     * True if a ping reports that the journal manager has accepts the terms of
     * use.
     *
     * @var bool
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $termsAccepted;

    /**
     * Email address to contact the journal manager.
     *
     * @var string
     * @Assert\Email
     * @ORM\Column(type="string", nullable=false)
     */
    private $email;

    /**
     * Name of the publisher.
     *
     * @var string
     * @ORM\Column(type="string", nullable=false)
     */
    private $publisherName;

    /**
     * Publisher's website.
     *
     * @var string
     * @Assert\Url
     * @ORM\Column(type="string", nullable=true)
     */
    private $publisherUrl;

    /**
     * The journal's deposits.
     *
     * @var Deposit[]|ArrayCollection
     * @ORM\OneToMany(targetEntity="Deposit", mappedBy="journal")
     */
    private $deposits;

    /**
     * Construct a new Journal.
     */
    public function __construct()
    {
        $this->deposits = new ArrayCollection();
        $this->publisherName = '';
        $this->termsAccepted = false;
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set uuid.
     *
     * @param string $uuid
     *
     * @return Journal
     */
    public function setUuid($uuid)
    {
        $this->uuid = strtoupper($uuid);

        return $this;
    }

    /**
     * Get uuid.
     *
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Set contacted.
     *
     * @param DateTime $contacted
     *
     * @return Journal
     */
    public function setContacted(DateTime $contacted)
    {
        $this->contacted = $contacted;

        return $this;
    }

    /**
     * Get contacted.
     *
     * @return DateTime
     */
    public function getContacted()
    {
        return $this->contacted;
    }

    /**
     * Set notified.
     *
     * @param DateTime $notified
     *
     * @return Journal
     */
    public function setNotified($notified)
    {
        $this->notified = $notified;

        return $this;
    }

    /**
     * Get notified.
     *
     * @return DateTime
     */
    public function getNotified()
    {
        return $this->notified;
    }

    /**
     * Set title.
     *
     * @param string $title
     *
     * @return Journal
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle()
    {
        if ($this->title) {
            return $this->title;
        }

        return '(unknown)';
    }

    /**
     * Set issn.
     *
     * @param string $issn
     *
     * @return Journal
     */
    public function setIssn($issn)
    {
        $this->issn = $issn;

        return $this;
    }

    /**
     * Get issn.
     *
     * @return string
     */
    public function getIssn()
    {
        return $this->issn;
    }

    /**
     * Set url.
     *
     * @param string $url
     *
     * @return Journal
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url.
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Get the plugin's Gateway URL to ping the journal.
     *
     * @return type
     */
    public function getGatewayUrl()
    {
        return $this->url.self::GATEWAY_URL_SUFFIX;
    }

    /**
     * Set status.
     *
     * @param string $status
     *
     * @return Journal
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status.
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set email.
     *
     * @param string $email
     *
     * @return Journal
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set publisherName.
     *
     * @param string $publisherName
     *
     * @return Journal
     */
    public function setPublisherName($publisherName)
    {
        $this->publisherName = $publisherName;

        return $this;
    }

    /**
     * Get publisherName.
     *
     * @return string
     */
    public function getPublisherName()
    {
        return $this->publisherName;
    }

    /**
     * Set publisherUrl.
     *
     * @param string $publisherUrl
     *
     * @return Journal
     */
    public function setPublisherUrl($publisherUrl)
    {
        $this->publisherUrl = $publisherUrl;

        return $this;
    }

    /**
     * Get publisherUrl.
     *
     * @return string
     */
    public function getPublisherUrl()
    {
        return $this->publisherUrl;
    }

    /**
     * Called automatically when the journal is updated, to set the contacted
     * timestamp.
     *
     * @ORM\PrePersist
     */
    public function setTimestamp()
    {
        $this->contacted = new DateTime();
    }

    /**
     * Add deposits.
     *
     * @param Deposit $deposit
     *
     * @return Journal
     */
    public function addDeposit(Deposit $deposit)
    {
        $this->deposits[] = $deposit;

        return $this;
    }

    /**
     * Remove deposits.
     *
     * @param Deposit $deposit
     */
    public function removeDeposit(Deposit $deposit)
    {
        $this->deposits->removeElement($deposit);
    }

    /**
     * Get deposits.
     *
     * @return Collection
     */
    public function getDeposits()
    {
        return $this->deposits;
    }

    /**
     * Get the deposits which have been sent to LOCKSSOMatic.
     *
     * @return ArrayCollection|Deposit[]
     */
    public function getCompletedDeposits()
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->eq('state', 'completed'))
        ;

        return $this->getDeposits()->matching($criteria);
    }

    /**
     * Get the deposits which have been set to LOCKSSOMatic, but which may not have
     * achieved agreement yet.
     *
     * Deposits returned will be in state deposited, complete, or status-error. Those
     * have all been sent to lockss.
     *
     * @return ArrayCollection|Deposit[]
     */
    public function getSentDeposits()
    {
        $criteria = Criteria::create()

src/AppBundle/Form/JournalType.php
<?php

/*
 * Copyright (C) 2015-2016 Michael Joyce <ubermichael@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Build a form to edit a blacklist entry.
 */
class JournalType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('uuid', new TextType(), array(
            'read_only' => true
        ));
        $builder->add('contacted', new DateType(), array(
            'widget' => 'single_text',
            'required' => false,
        ));
        $builder->add('termsAccepted');
        $builder->add('notified', new DateType(), array(
            'widget' => 'single_text',
            'required' => false,
        ));
        $builder->add('title');
        $builder->add('ojsVersion');
        $builder->add('issn');
        $builder->add('url', new UrlType());
        $builder->add('status');
        $builder->add('email', new EmailType());
        $builder->add('publisherName');
        $builder->add('publisherUrl', new UrlType());
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Journal',
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'appbundle_journal';
    }
}

src/AppBundle/Resources/views/Journal/delete.html.twig
{% extends '::base.html.twig' %}


{% block pageheader %}
    <h1>Delete Journal</h1>

    <p>
        {% if entity.countDeposits() > 0 %}
            Once a journal has made deposits it cannot be deleted.
        {% else %}
            Are you sure you want to delete this journal?
        {% endif %}
    </p>
{% endblock %}

{% block body -%}
    <div class="btn-toolbar">
        <div class="btn-group pull-right">
            <a href="{{ path('journal') }}" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span> Back
            </a>
        </div>
    </div>

    <table class="record_properties table table-striped table-bordered table-hover">
        <tbody>
            <tr>
                <th>Uuid</th>
                <td>{{ entity.uuid }}</td>
            </tr>
            <tr>
                <th>Contacted</th>
                <td>{{ entity.contacted|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Terms Accepted</th>
                <td>{% if entity.termsAccepted %}Yes{% else %}No{% endif %}</td>
            </tr>
            <tr>
                <th>Notified</th>
                <td>
                    {% if entity.notified %}
                        {{ entity.notified|date('Y-m-d H:i:s') }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ entity.title }}</td>
            </tr>
            <tr>
                <th>OJS Version</th>
                <td>{{ entity.ojsVersion }}</td>
            </tr>
            <tr>
                <th>Issn</th>
                <td>{{ entity.issn }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td><a href="{{ entity.url }}">{{ entity.url|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
            </tr>
            <tr>
                <th>Ping Url</th>
                <td><a href="{{ entity.gatewayUrl }}">{{entity.gatewayUrl|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
            </tr>
            <tr>
                <th>Service Document</th>
                <td><a href="{{ url('service_document', {'On-Behalf-Of': entity.uuid, 'Journal-Url': entity.url} ) }}">XML</a></td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ entity.status }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td><a href="mailto:{{ entity.email }}">{{ entity.email }}</a></td>
            </tr>
            <tr>
                <th>Publisher Name</th>
                <td>{{ entity.publisherName }}</td>
            </tr>
            <tr>
                <th>Publisher Url</th>
                <td><a href="{{ entity.publisherUrl }}">{{ entity.publisherUrl|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
            </tr>
            <tr>
                <th>Deposits</th>
                <td>
                    <a href="{{ path('journal_deposits', {'id': entity.id}) }}">
                        {{ entity.countDeposits() }}
                    </a>
                </td>
            </tr>    
            <tr>
                <th>Permissions</th>
                <td>
                    {% if blackwhitelist.isWhitelisted(entity.uuid) %}
                        Whitelisted
                    {% elseif blackwhitelist.isBlacklisted(entity.uuid) %}
                        Blacklisted
                    {% endif %}				
                </td>
            </tr>
        </tbody>
    </table>

    {% if entity.countDeposits() > 0 %}
        <p>Once a journal has made deposits it cannot be deleted.</p>
    {% else %}

        {{ form(form) }}

    {% endif %}


{% endblock %}

src/AppBundle/Resources/views/Journal/deposits.html.twig
{% extends '::base.html.twig' %}


{% block pageheader %}
    <h1>Deposit List</h1>
{% endblock %}

{% block body -%}

<p>Showing deposits for {{ journal.title }}</p>

    <table class="records_list table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Deposit Uuid</th>
                <th>Received</th>
                <th>Action</th>
                <th>Volume</th>
                <th>Issue</th>
                <th>Pubdate</th>
                <th>Url</th>
                <th>Size</th>
                <th>State</th>
                <th>Plnstate</th>
            </tr>
        </thead>
        <tbody>
            {% for entity in entities %}
                <tr>
                    <td><a href="{{ path('deposit_show', { 'id': entity.id }) }}">{{ entity.deposituuid }}</a></td>
                    <td>{% if entity.received %}{{ entity.received|date('Y-m-d H:i:s') }}{% endif %}</td>
                    <td>{{ entity.action }}</td>
                    <td>{{ entity.volume }}</td>
                    <td>{{ entity.issue }}</td>
                    <td>{% if entity.pubDate %}{{ entity.pubDate|date('Y-m-d') }}{% endif %}</td>
                    <td>{{ entity.url }}</td>
                    <td>{{ entity.size }}</td>
                    <td>{{ entity.state }}</td>
                    <td>{{ entity.plnState }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="navigation">
        {{ knp_pagination_render(entities) }}
    </div>

{% endblock %}

src/AppBundle/Resources/views/Journal/edit.html.twig
{% extends '::base.html.twig' %}


{% block pageheader %}
    <h1>Edit Journal</h1>
    <p>Use this form to edit a journal's metadata.</p>
{% endblock %}

{% block body -%}
    <div class="btn-toolbar">
        <div class="btn-group pull-right">
            <a href="{{ path('journal_show', {'id': entity.id}) }}" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span> Back
            </a>
        </div>
    </div>

    {{ form(edit_form) }}


{% endblock %}

src/AppBundle/Resources/views/Journal/index.html.twig
{% extends '::base.html.twig' %}


{% block pageheader %}
    <h1>Journal List</h1>
    <p class="count">
        Displaying {{ entities|length }} records of {{ entities.getTotalItemCount }} total.
    </p>
{% endblock %}

{% block body -%}

    <div class="row">
        <div class="col-sm-2">
            <div class="panel panel-default">
                <div class="panel-heading"><strong>Filter</strong></div>
                <div class="panel-body">
					<p>Filter the list of journals with these links.</p>
				</div>
				<ul class='list-group'>
				{% for status in statuses %}
					<li class='list-group-item'><a href="{{path('journal', { 'status': status.status })}}">{{ status.status }}</a><span class='badge'>{{status.ct}}</span></li>
				{% endfor %}
					<li class='list-group-item'><a href="{{path('journal')}}">All Journals</a></li>
				</ul>
            </div>
        </div>
        <div class="col-sm-10">

            <div class="btn-toolbar">
                <div class="btn-group pull-right">
                    <a href="{{ path('journal_search') }}" class="btn btn-default">
                        <span class="glyphicon glyphicon-search"></span> Search
                    </a>
                </div>
            </div>

            <table class="table table-striped table-condensed table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Contacted</th>
                        <th>Status</th>
                        <th>OJS</th>
                        <th>Url</th>
                    </tr>
                </thead>
                <tbody>
                    {% for entity in entities %}
                        <tr>
                            <td><a href="{{ path('journal_show', { 'id': entity.id }) }}">{{ entity.title }}</a></td>
                            <td>{% if entity.contacted %}{{ entity.contacted|date('Y-m-d H:i:s') }}{% endif %}</td>
                            <td>{{ entity.status }}</td>
                            <td>{{ entity.ojsVersion }}</td>
                            <td><a href="{{ entity.url }}">{{ entity.url|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>


            <div class="navigation">
                {{ knp_pagination_render(entities) }}
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Journal/ping.html.twig
{% extends '::base.html.twig' %}


{% block pageheader %}
    <h1>Journal</h1>
{% endblock %}

{% block body -%}
    <div class="btn-toolbar">
        <div class="btn-group pull-right">
            <a href="{{ path('journal_show', {'id': entity.id}) }}" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span> Back
            </a>
            <a href="{{ path('journal_ping', {'id': entity.id}) }}" class="btn btn-default ping">
                <span class="glyphicon glyphicon-refresh"></span> Ping
            </a>
        </div>
    </div>

    <table class="record_properties table table-striped table-bordered table-hover">
        <tbody>
            <tr>
                <th>Title</th>
                <td>{{ entity.title }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td><a href="{{ entity.url }}">{{ entity.url|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
            </tr>
            <tr>
                <th>Ping Url</th>
                <td><a href="{{ entity.getGatewayUrl() }}">{{ entity.getGatewayUrl()|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ entity.status }}</td>
            </tr>
        </tbody>
    </table>

	<h2>Ping Result</h2>
    <dl class="dl-horizontal">
		<dt>OJS Version</dt>
		<dd>{{ ping.getOjsRelease() }}</dd>
		<dt>Plugin Version</dt>
		<dd>{{ ping.getPluginReleaseVersion() }}</dd>
		<dt>Plugin Date</dt>
		<dd>{{ ping.getPluginReleaseDate() }}</dd>
		<dt>Plugin Current</dt>
		<dd>{{ ping.isPluginCurrent() }}</dd>
		<dt>Terms accepted</dt>
		<dd>{{ ping.areTermsAccepted() }}</dd>		
		<dt>Journal Title</dt>
		<dd>{{ ping.getJournalTitle() }}</dd>
		<dt>Article Count</dt>
		<dd>{{ ping.getArticleCount() }}</dd>
		<dt>Recent Articles</dt>
		<dd>
			<ul class='list-unstyled'>
				{% for article in ping.getArticleTitles() %}
					<li>
						{{ article.title }} <br />
						<span class='text-muted'>{{article.date}}</span>
					</li>
				{% endfor %}
			</ul>
		</dd>
	</dl>


{% endblock %}

src/AppBundle/Resources/views/Journal/show.html.twig
{% extends '::base.html.twig' %}


{% block pageheader %}
    <h1>Journal</h1>
{% endblock %}

{% block body -%}
    <div class="btn-toolbar">
        <div class="btn-group pull-right">
            <a href="{{ path('journal') }}" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span> Back
            </a>
            <a href="{{ path('journal_edit', {'id': entity.id}) }}" class="btn btn-default ping">
                <span class="glyphicon glyphicon-edit"></span> Edit
            </a>
            <a href="{{ path('journal_ping', {'id': entity.id}) }}" class="btn btn-default ping">
                <span class="glyphicon glyphicon-refresh"></span> Ping
            </a>
        </div>
    </div>

    <table class="record_properties table table-striped table-bordered table-hover">
        <tbody>
            <tr>
                <th>Uuid</th>
                <td>{{ entity.uuid }}</td>
            </tr>
            <tr>
                <th>Contacted</th>
                <td>{{ entity.contacted|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Terms Accepted</th>
                <td>{% if entity.termsAccepted %}Yes{% else %}No{% endif %}</td>
            </tr>
            <tr>
                <th>Notified</th>
                <td>
                    {% if entity.notified %}
                        {{ entity.notified|date('Y-m-d H:i:s') }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ entity.title }}</td>
            </tr>
            <tr>
                <th>OJS Version</th>
                <td>{{ entity.ojsVersion }}</td>
            </tr>
            <tr>
                <th>Issn</th>
                <td>{{ entity.issn }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td><a href="{{ entity.url }}">{{ entity.url|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
            </tr>
            <tr>
                <th>Ping Url</th>
                <td><a href="{{ entity.gatewayUrl }}">{{entity.gatewayUrl|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
            </tr>
            <tr>
                <th>Service Document</th>
                <td><a href="{{ url('service_document', {'On-Behalf-Of': entity.uuid, 'Journal-Url': entity.url} ) }}">XML</a></td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ entity.status }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td><a href="mailto:{{ entity.email }}">{{ entity.email }}</a></td>
            </tr>
            <tr>
                <th>Publisher Name</th>
                <td>{{ entity.publisherName }}</td>
            </tr>
            <tr>
                <th>Publisher Url</th>
                <td><a href="{{ entity.publisherUrl }}">{{ entity.publisherUrl|preg_replace('~/~', '/&#8203;')|raw }}</a></td>
            </tr>
            <tr>
                <th>Deposits</th>
                <td>
                    <a href="{{ path('journal_deposits', {'id': entity.id}) }}">
                        {{ entity.countDeposits() }}
                    </a>
                </td>
            </tr>    
            <tr>
                <th>Permissions</th>
                <td>
                    {% if blackwhitelist.isWhitelisted(entity.uuid) %}
                        Whitelisted
                    {% elseif blackwhitelist.isBlacklisted(entity.uuid) %}
                        Blacklisted
                    {% endif %}				
                </td>
            </tr>
        </tbody>
    </table>

    {% if entity.status == 'unhealthy' %}
        <p>This journal has not contacted the PLN in quite some time. You can update its status:<br/>
            <a class='btn btn-default' href="{{ path('journal_status', {'id': entity.id, 'status': 'healthy'}) }}">Healthy</a>
            <a class='btn btn-default' href="{{ path('journal_status', {'id': entity.id, 'status': 'triggered'}) }}">Triggered</a>
            <a class='btn btn-default' href="{{ path('journal_status', {'id': entity.id, 'status': 'dead'}) }}">Dead (do not trigger)</a>
        </p>
    {% endif %}

{% endblock %}

src/AppBundle/Resources/views/Journal/showDeposits.html.twig
{% extends '::base.html.twig' %}


{% block pageheader %}
    <h1>Deposit List</h1>
{% endblock %}

{% block body -%}

<p>Showing deposits for {{ journal.title }}</p>

    <div class="btn-toolbar">
        <div class="btn-group pull-right">
            <a href="{{ path('journal_show', {'id': journal.id}) }}" class="btn btn-default">
                <span class="glyphicon glyphicon-arrow-left"></span> Journal
            </a>
        </div>
    </div>
    <table class="records_list table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Deposit Uuid</th>
                <th>Received</th>
                <th>Action</th>
                <th>Volume</th>
                <th>Issue</th>
                <th>State</th>
                <th>PLN State</th>
            </tr>
        </thead>
        <tbody>
            {% for entity in entities %}
                <tr>
                    <td><a href="{{ path('deposit_show', { 'id': entity.id }) }}">{{ entity.deposituuid }}</a></td>
                    <td>{% if entity.received %}{{ entity.received|date('Y-m-d H:i:s') }}{% endif %}</td>
                    <td>{{ entity.action }}</td>
                    <td>{{ entity.volume }}</td>
                    <td>{{ entity.issue }}</td>
                    <td>{{ entity.state }}</td>
                    <td>{{ entity.plnState }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="navigation">
        {{ knp_pagination_render(entities) }}
    </div>

{% endblock %}